#!/usr/bin/env python

from src import search
from src import scanner
from src import crawler


google = search.Google()

sites = ["www.icdcprague.org/index.php?id=10",
         "www.sallatykka.com/web/index.php?id=31&page=1"
        ]

#print(scanner.scan(sites[0]))
#print(crawler.crawl("http://www.icdcprague.org/"))
print(crawler.crawl(sites[1]))
